/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FetchHeaders {
  get(name: string): string | null
  has(name: string): boolean
  entries(): Array<Array<string>>
  keys(): Array<string>
  values(): Array<string>
}

export declare class FetchResponse {
  readonly status: number
  readonly statusText: string
  readonly ok: boolean
  readonly url: string
  readonly redirected: boolean
  get headers(): FetchHeaders
  arrayBuffer(): Promise<Buffer>
}

/**
 * Clears all cached clients. Intended for controlled shutdown or test/setup
 * boundaries; it also drops all in-memory session cookies.
 */
export declare function clearClientCache(): number

/**
 * Removes every cached client for a session, along with the session's shared
 * in-memory cookie jar. Existing in-flight requests continue with their
 * already-cloned client (and its reference to the old jar).
 */
export declare function clearSession(session: string): number

export declare function fetch(url: string, options?: FetchOptions | undefined | null): Promise<FetchResponse>

export interface FetchOptions {
  method?: string
  headers?: Record<string, string>
  /**
   * Request body. Accepts either a UTF-8 string or raw bytes
   * (`Uint8Array`/`Buffer`). Higher-level shapes (`URLSearchParams`,
   * `Blob`, `ArrayBuffer`, typed arrays) are normalized to one of these two
   * by the JS wrapper before they reach here; `FormData`/multipart is not
   * supported (it would diverge the fingerprint — see README).
   */
  body?: string | Uint8Array
  /**
   * Browser/client fingerprint to emulate. Accepts either a native
   * wreq-util profile name ("chrome_147", "safari_26", "firefox_142"),
   * a curl-impersonate preset name ("chrome116", "ff109", "safari15_5" —
   * see `listImpersonatePresets()`), or "random" / "weighted_random".
   * Defaults to "chrome_147".
   */
  impersonate?: string
  /**
   * Overrides the platform `impersonate` declares in headers/User-Agent:
   * "windows", "macos", "linux", "android", or "ios". Defaults to
   * whatever `impersonate` resolves to (a curl-impersonate preset's own
   * platform, or "macos" for a bare wreq-util profile name). Unlike
   * `tlsOptions`, this does **not** diverge the TLS fingerprint — it only
   * changes declared-platform headers (`sec-ch-ua-platform`, User-Agent),
   * which is exactly what you want when e.g. running in a Linux container
   * and need the declared platform to match the host's real TCP/IP stack
   * instead of clashing with it. No effect when `impersonate` is
   * "random"/"weighted_random". Client-level — see `session`.
   */
  platform?: string
  /**
   * Proxy URL for this request, e.g. "http://user:pass@host:3128" or
   * "socks5://host:1080". Applied per request; does not affect which
   * client/connection-pool this call reuses.
   */
  proxy?: string
  /**
   * Pin the request hostname to one or more literal IP addresses while
   * keeping the original hostname for TLS SNI, certificate validation, and
   * the Host header. Keys are "host" or "host:port"; bracket IPv6 keys
   * when adding a port. Only the URL's initial host is considered, and a
   * port-specific entry takes precedence over a host-only entry. Redirects
   * to another host are not pinned, even if that host is also in this map:
   * SSRF-sensitive callers must use `redirect: "manual"`, validate each
   * Location, and provide a new pin per hop. Ignored when `proxy` is set
   * because the proxy performs resolution.
   * Requests carrying this option use a one-off client rather than the
   * process-wide client cache; with `session` set, the one-off client
   * still shares that session's cookie jar.
   */
  resolve?: Record<string, string | Array<string>>
  /**
   * WHATWG redirect handling: "follow" (the default), "manual" (return the
   * 3xx response), or "error" (reject on a redirect). Per-request: calls on
   * the same `session` share one client and cookie jar regardless of their
   * redirect mode.
   */
  redirect?: string
  /**
   * Opaque session id. Calls sharing the same (`impersonate`, `platform`,
   * `session`, `tlsMinVersion`, `tlsMaxVersion`, `httpVersion`) reuse one
   * underlying client, and the persistent cookie jar is keyed by the
   * session id alone — cookies carry across calls, fingerprint settings,
   * and `resolve` one-off clients the way they would in a real browser
   * tab. Omit for stateless, cookie-less calls (the default) — this avoids
   * unrelated callers on the same profile ever sharing cookies by
   * accident.
   */
  session?: string
  /** Overall request timeout in milliseconds. */
  timeoutMs?: number
  /** Maximum buffered response body size in bytes. Defaults to 32 MiB. */
  maxResponseBytes?: number
  /**
   * Minimum TLS version to offer during the handshake: "1.0", "1.1",
   * "1.2", or "1.3". Client-level — see `session`.
   */
  tlsMinVersion?: string
  /**
   * Maximum TLS version to offer during the handshake. Client-level —
   * see `session`.
   */
  tlsMaxVersion?: string
  /**
   * Force a specific HTTP version instead of negotiating via ALPN:
   * "http1" or "http2". Client-level — see `session`.
   */
  httpVersion?: string
  /**
   * Raw ClientHello overrides layered on top of `impersonate`'s own TLS
   * config. Unset fields keep the preset's values; set fields diverge the
   * fingerprint from a "pure" `impersonate` profile by definition — only
   * use this when you specifically need bytes the preset doesn't offer.
   * Client-level — see `session`.
   */
  tlsOptions?: TlsOptionsOverride
}

export interface ImpersonatePresetInfo {
  /** curl-impersonate preset name (e.g. "chrome116"). */
  name: string
  /** Underlying wreq-util profile this preset resolves to (e.g. "chrome_116"). */
  profile: string
  platform: string
  /** Browser version curl-impersonate pinned this preset to. */
  browserVersion: string
  /**
   * `false` means curl-impersonate's pinned version predates wreq-util's
   * oldest profile for that browser family, so `profile` is the closest
   * available approximation rather than a byte-exact fingerprint match.
   */
  exact: boolean
}

/**
 * Lists every curl-impersonate (https://github.com/lwthiker/curl-impersonate)
 * preset name accepted by `impersonate`, and what it actually resolves to.
 */
export declare function listImpersonatePresets(): Array<ImpersonatePresetInfo>

export interface TlsOptionsOverride {
  /**
   * OpenSSL-format cipher list, e.g. the same string curl-impersonate's
   * wrapper scripts pass to `--ciphers`.
   */
  cipherList?: string
  /** OpenSSL-format supported-curves list (curl's `--curves`). */
  curvesList?: string
  /** OpenSSL-format signature-algorithms list. */
  sigalgsList?: string
  /** Randomize ClientHello extension order (curl's `--tls-permute-extensions`). */
  permuteExtensions?: boolean
  /** Whether to offer TLS session tickets (RFC 5077). */
  sessionTicket?: boolean
}
