/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FetchHeaders {
  get(name: string): string | null
  has(name: string): boolean
  entries(): Array<Array<string>>
  keys(): Array<string>
  values(): Array<string>
}

export declare class FetchResponse {
  readonly status: number
  readonly statusText: string
  readonly ok: boolean
  readonly url: string
  readonly redirected: boolean
  get headers(): FetchHeaders
  text(): Promise<string>
  json(): Promise<any>
  arrayBuffer(): Promise<Buffer>
}

export declare function fetch(url: string, options?: FetchOptions | undefined | null): Promise<FetchResponse>

export interface FetchOptions {
  method?: string
  headers?: Record<string, string>
  body?: string
  /**
   * Browser/client fingerprint to emulate. Accepts either a native
   * wreq-util profile name ("chrome_147", "safari_26", "firefox_142"),
   * a curl-impersonate preset name ("chrome116", "ff109", "safari15_5" —
   * see `listImpersonatePresets()`), or "random" / "weighted_random".
   * Defaults to "chrome_147".
   */
  impersonate?: string
  /**
   * Proxy URL for this request, e.g. "http://user:pass@host:3128" or
   * "socks5://host:1080". Applied per request; does not affect which
   * client/connection-pool this call reuses.
   */
  proxy?: string
  /**
   * Opaque session id. Calls sharing the same (`impersonate`, `session`,
   * `tlsMinVersion`, `tlsMaxVersion`, `httpVersion`) reuse one underlying
   * client with a persistent cookie jar, so cookies carry across calls the
   * way they would in a real browser tab. Omit for stateless, cookie-less
   * calls (the default) — this avoids unrelated callers on the same
   * profile ever sharing cookies by accident.
   */
  session?: string
  /** Overall request timeout in milliseconds. */
  timeoutMs?: number
  /**
   * Minimum TLS version to offer during the handshake: "1.0", "1.1",
   * "1.2", or "1.3". Client-level — see `session`.
   */
  tlsMinVersion?: string
  /**
   * Maximum TLS version to offer during the handshake. Client-level —
   * see `session`.
   */
  tlsMaxVersion?: string
  /**
   * Force a specific HTTP version instead of negotiating via ALPN:
   * "http1" or "http2". Client-level — see `session`.
   */
  httpVersion?: string
  /**
   * Raw ClientHello overrides layered on top of `impersonate`'s own TLS
   * config. Unset fields keep the preset's values; set fields diverge the
   * fingerprint from a "pure" `impersonate` profile by definition — only
   * use this when you specifically need bytes the preset doesn't offer.
   * Client-level — see `session`.
   */
  tlsOptions?: TlsOptionsOverride
}

export interface ImpersonatePresetInfo {
  /** curl-impersonate preset name (e.g. "chrome116"). */
  name: string
  /** Underlying wreq-util profile this preset resolves to (e.g. "chrome_116"). */
  profile: string
  platform: string
  /** Browser version curl-impersonate pinned this preset to. */
  browserVersion: string
  /**
   * `false` means curl-impersonate's pinned version predates wreq-util's
   * oldest profile for that browser family, so `profile` is the closest
   * available approximation rather than a byte-exact fingerprint match.
   */
  exact: boolean
}

/**
 * Lists every curl-impersonate (https://github.com/lwthiker/curl-impersonate)
 * preset name accepted by `impersonate`, and what it actually resolves to.
 */
export declare function listImpersonatePresets(): Array<ImpersonatePresetInfo>

export interface TlsOptionsOverride {
  /**
   * OpenSSL-format cipher list, e.g. the same string curl-impersonate's
   * wrapper scripts pass to `--ciphers`.
   */
  cipherList?: string
  /** OpenSSL-format supported-curves list (curl's `--curves`). */
  curvesList?: string
  /** OpenSSL-format signature-algorithms list. */
  sigalgsList?: string
  /** Randomize ClientHello extension order (curl's `--tls-permute-extensions`). */
  permuteExtensions?: boolean
  /** Whether to offer TLS session tickets (RFC 5077). */
  sessionTicket?: boolean
}
